{
  "formatVersion": "1.1",
  "component": {
    "group": "maven.zzt",
    "module": "transform",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "transform-1.1.2.jar",
          "url": "transform-1.1.2.jar",
          "size": 25462,
          "sha512": "b22013380b3f253506400f7393dc7819411300ce187bb64e0eda48469a7343c8fe5dc84c124cc822081b18c4d07f4efe155d9caacf4673c7fa1ff65fbfb421d5",
          "sha256": "fe81c21ea2f011b158b06e165f9ca25f58e01f04f973c51e4f6bf3302dbaffe8",
          "sha1": "5c6a27722b86df0144f053b039b3f9655b5d69b2",
          "md5": "ffb3d115097382ac3ac57b59179780e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-gradle-plugin",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.ajoberstar",
          "module": "grgit",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "transform-1.1.2.jar",
          "url": "transform-1.1.2.jar",
          "size": 25462,
          "sha512": "b22013380b3f253506400f7393dc7819411300ce187bb64e0eda48469a7343c8fe5dc84c124cc822081b18c4d07f4efe155d9caacf4673c7fa1ff65fbfb421d5",
          "sha256": "fe81c21ea2f011b158b06e165f9ca25f58e01f04f973c51e4f6bf3302dbaffe8",
          "sha1": "5c6a27722b86df0144f053b039b3f9655b5d69b2",
          "md5": "ffb3d115097382ac3ac57b59179780e2"
        }
      ]
    }
  ]
}
