{
  "formatVersion": "1.1",
  "component": {
    "group": "maven.zzt",
    "module": "transform",
    "version": "1.0.0.08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "transform-1.0.0.08.jar",
          "url": "transform-1.0.0.08.jar",
          "size": 15317,
          "sha512": "140107032501f50fdc4f028278d6dbbf2cad8b6ed9f5e969fe1fe4d385bfc7ac753e1b43a6bf960563c75d16b2ae7804e25777cef3f841023feec015d306c3f5",
          "sha256": "e453f881fab56017cb29cd6d7f0ed625f45538775f7dbb7f471ad968cb0fda02",
          "sha1": "7660a1799a28da5a9e336166da863361f9806d5e",
          "md5": "0cc554a8868f323984ee5192758b551f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "transform-1.0.0.08.jar",
          "url": "transform-1.0.0.08.jar",
          "size": 15317,
          "sha512": "140107032501f50fdc4f028278d6dbbf2cad8b6ed9f5e969fe1fe4d385bfc7ac753e1b43a6bf960563c75d16b2ae7804e25777cef3f841023feec015d306c3f5",
          "sha256": "e453f881fab56017cb29cd6d7f0ed625f45538775f7dbb7f471ad968cb0fda02",
          "sha1": "7660a1799a28da5a9e336166da863361f9806d5e",
          "md5": "0cc554a8868f323984ee5192758b551f"
        }
      ]
    }
  ]
}
